{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.utility",
    "module": "java-resource-loader",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "java-resource-loader-1.0.jar",
          "url": "java-resource-loader-1.0.jar",
          "size": 4961,
          "sha512": "174572ea1c73641cd8a11a002b09819dafc509eea3003189a3070a51ac833e0c7ff6e18222f2f85cdaa0888c66b9090d835e42ec7ad57b80b28dc1c8a66269ee",
          "sha256": "f1c24307341193091a0923b6939fbdba8e9014536194072dcc569b5281d07e10",
          "sha1": "cacf432d04aa67d9f3480333157558b2127f3388",
          "md5": "1bb101bfb164cf5bd828618b4db0861a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "java-resource-loader-1.0.jar",
          "url": "java-resource-loader-1.0.jar",
          "size": 4961,
          "sha512": "174572ea1c73641cd8a11a002b09819dafc509eea3003189a3070a51ac833e0c7ff6e18222f2f85cdaa0888c66b9090d835e42ec7ad57b80b28dc1c8a66269ee",
          "sha256": "f1c24307341193091a0923b6939fbdba8e9014536194072dcc569b5281d07e10",
          "sha1": "cacf432d04aa67d9f3480333157558b2127f3388",
          "md5": "1bb101bfb164cf5bd828618b4db0861a"
        }
      ]
    }
  ]
}
